"""Column names on MealItemNutrition used when persisting CSV-derived rows (excluding id, meal_item_id, created_at)."""

MEAL_ITEM_NUTRITION_KEYS: tuple[str, ...] = (
    "calories",
    "protein_g",
    "fat_g",
    "carbs_g",
    "fiber_g",
    "sugar_g",
    "saturated_fat_g",
    "sodium_mg",
    "calcium_mg",
    "magnesium_mg",
    "potassium_mg",
    "phosphorus_mg",
    "iron_mg",
    "zinc_mg",
    "selenium_mcg",
    "copper_mg",
    "manganese_mg",
    "vitamin_a_mcg",
    "vitamin_c_mg",
    "vitamin_d_mcg",
    "vitamin_e_mg",
    "vitamin_k_mcg",
    "vitamin_b6_mg",
    "vitamin_b12_mcg",
    "folate_mcg",
    "thiamin_mg",
    "riboflavin_mg",
    "niacin_mg",
    "pantothenic_acid_mg",
    "choline_mg",
)
