import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#eeeeee",
        "on-secondary-fixed-variant": "#454747",
        "error-container": "#ffdad6",
        surface: "#f9f9f9",
        "on-secondary-container": "#616363",
        "on-primary-fixed-variant": "#005228",
        "on-primary": "#ffffff",
        "outline-variant": "#bbcbbb",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "on-primary-container": "#005027",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "on-surface": "#1a1c1c",
        "on-secondary-fixed": "#1a1c1c",
        outline: "#6c7b6d",
        "inverse-surface": "#2f3131",
        "surface-container-low": "#f3f3f3",
        "primary-fixed-dim": "#4ae183",
        background: "#f9f9f9",
        "on-tertiary-container": "#772e14",
        "on-surface-variant": "#3d4a3e",
        "inverse-on-surface": "#f1f1f1",
        "tertiary-container": "#ff9875",
        "surface-variant": "#e2e2e2",
        "primary-container": "#2ecc71",
        "secondary-fixed-dim": "#c6c6c7",
        "tertiary-fixed-dim": "#ffb59d",
        "on-background": "#1a1c1c",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#390c00",
        "on-tertiary-fixed-variant": "#793015",
        "secondary-container": "#dfe0e0",
        "surface-dim": "#dadada",
        "surface-tint": "#006d37",
        "surface-bright": "#f9f9f9",
        tertiary: "#98472a",
        "tertiary-fixed": "#ffdbd0",
        "secondary-fixed": "#e2e2e2",
        "inverse-primary": "#4ae183",
        primary: "#006d37",
        "primary-fixed": "#6bfe9c",
        "on-primary-fixed": "#00210c",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e8e8e8",
        secondary: "#5d5f5f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        gutter: "16px",
        md: "16px",
        lg: "24px",
        xs: "4px",
        margin: "24px",
        unit: "8px",
        sm: "8px",
      },
      fontFamily: {
        h2: ["Inter", "sans-serif"],
        h1: ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        h3: ["Inter", "sans-serif"],
      },
      fontSize: {
        h2: ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        h1: ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
