from typing import Any
import base64
import binascii
from fastapi import FastAPI, HTTPException, Request


class LLMAssistant:
    """
    Stub class to simulate the behavior of a real LLM assistant.
    """

    def generate_response(self, image_data: str, timeout: int = 10) -> Any:
        """
        Simulates the generation of nutritional information based on image data.
        """
        return {
            "status": "success",
            "result": {
                "calories": 100,
                "proteins": 10,
                "fats": 20,
                "carbohydrates": 30,
            },
            "error": "",
        }


# Initialize FastAPI app
app = FastAPI()

# Instance of the stub assistant
assistant = LLMAssistant()


@app.post("/generate_response")
async def generate_response(request: Request) -> Any:
    """
    Generates a response based on the Base64-encoded image string provided in the request.

    Args:
        The request should contain a JSON body with a 'image_base64' field that contains
        the Base64 encoded image data.

    Returns:
        Any: The response generated by the assistant.

    Raises:
        HTTPException:
            - 400: If the Base64 decoding fails.
            - 504: If a TimeoutError occurs.
            - 500: If an unexpected error occurs.
    """

    # 1. Read JSON body
    data = await request.json()

    # 2. Validate
    if "image_base64" not in data:
        raise HTTPException(status_code=400, detail="'image_base64' field is required")

    image_base64 = data["image_base64"]

    # 3. Try to decode Base64
    try:
        base64.b64decode(image_base64)
    except (binascii.Error, ValueError):
        raise HTTPException(status_code=400, detail="Invalid Base64 image data")

    # 4. Call assistant with error handling
    try:
        response = assistant.generate_response(image_base64)

    except TimeoutError as detail:
        raise HTTPException(status_code=504, detail=str(detail))

    except Exception as detail:
        raise HTTPException(status_code=500, detail=str(detail))

    return response
